### ISSUE TITLE
Any idea why? (can't find log error)

### ISSUE THREAD

**Issue by dukenuking** [licoffe/POE-Stash-indexer#1]
Looks like a nice tool, I've tried on debian 4.7.5.-1 and I'm getting following(also ctrl+c doesn't kill the proces gotta manualy kill nodejs):
2-10-2016 12:22:26 > [Indexer] Connected to MongoDB.
2-10-2016 12:22:26 > [Indexer] Attempting to create or reuse POE_price collection
2-10-2016 12:22:26 > [Indexer] Last chunk ID found
2-10-2016 12:22:26 > [Indexer] Found 0 entries
2-10-2016 12:22:26 > [Indexer] Starting new indexation
2-10-2016 12:22:26 > [Indexer] Downloading compressed data[]
2-10-2016 12:22:31 > [Indexer] Downloaded
2-10-2016 12:22:31 > [Indexer] Extracting data
2-10-2016 12:22:31 > [Indexer] Error occured, retrying
2-10-2016 12:22:33 > [Indexer] Downloading compressed data[]
2-10-2016 12:22:37 > [Indexer] Downloaded
2-10-2016 12:22:37 > [Indexer] Extracting data
2-10-2016 12:22:37 > [Indexer] Error occured, retrying

using nodejs v4.3.1
It's like he is not getting the id or something?

**Comment by licoffe** [comment]
Hi, thanks for trying my code! The indexer needs a **data** folder in the project folder. Since this is not created automatically and not pushed with git, that may be the issue. Also Ctrl + C is not working since the interrupt signal gets caught in order to stop the indexer at the right moment, not to corrupt data.

**Comment by dukenuking** [comment]
I've created the data folder, and he is effectivly downloading it, but I think it's nog getting chunck id
as I have 2 files in data folder -> data_.gzip and data_.json where .gzip is around 9mb and json is like 0bytes...

**Comment by licoffe** [comment]
Mmmm, do you have the 'gunzip' command installed?
Could you try to manually run this `gunzip -S '' --force -c ./data/data_.gzip > ./data/data_.json`?

**Comment by dukenuking** [comment]
gunzip -V
gzip 1.6
Copyright (C) 2007, 2010, 2011 Free Software Foundation, Inc.
Copyright (C) 1993 Jean-loup Gailly.
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License http://www.gnu.org/licenses/gpl.html.
There is NO WARRANTY, to the extent permitted by law.

Written by Jean-loup Gailly.

Is it normal that the downloaded gzip is named -> data_.gzip?

**Comment by dukenuking** [comment]
gzip: invalid suffix ''
ok, I think I know =) gonna try something

**Comment by dukenuking** [comment]
I've removed the '' -> now getting another error :D :
2-10-2016 12:55:52 > [Indexer] There was an error inserting value: undefined
Loading data into DB: 2377ms
2-10-2016 12:55:52 > [Indexer] Next ID: 6892-7570-6012-10171-3898
2-10-2016 12:55:52 > [Indexer] Cleaning up

**Comment by licoffe** [comment]
That's an error festival :D Could you send me the full logs?

**Comment by dukenuking** [comment]
Haha sure, only it doesnt crate the log.txt for some reason...
Edit, edited indexer.js to ./log.txt -> now it works but it spits the "undefined" messange when inserting

**Comment by licoffe** [comment]
Sorry, I ment the the content of the terminal window when running the indexer.

**Comment by dukenuking** [comment]
Here a pastebin, http://pastebin.com/rCxve6Nf

I guess he can't incert some value? (anyway to enable some debug?)

**Comment by licoffe** [comment]
Thanks a lot! I'll check this out. I pushed a last commit which should fix the two previous issues you encountered (data folder creation and gunzip issues).

**Comment by dukenuking** [comment]
Nice! Thanks for quick reply =)

**Comment by licoffe** [comment]
@dukenuking I managed to get everything working on Ubuntu (http://imgur.com/vvB1c3e). Could you give it a try again when you have time?
