### ISSUE TITLE
First search works, but others don't

### ISSUE THREAD

**Issue by drdread987** [licoffe/POE-Stash-indexer#11]
I am currently running in to a problem where my first search works as long as I don't change any of the parameters, but any search thereafter is only returning 0 results.

**Comment by licoffe** [comment]
Hi, I am not running the backend anymore as a service so queries won't work.

**Comment by drdread987** [comment]
I am connecting to my own SQL server, just it is wierd with how only the first query returns results but none thereafter. I did change the config for the query tool to match my server.
