### ISSUE TITLE
Insertion issues with MongoDB

### ISSUE THREAD

**Issue by licoffe** [licoffe/POE-Stash-indexer#2]
As mentionned by @dukenuking:
2-10-2016 12:55:52 > [Indexer] There was an error inserting value: undefined
Loading data into DB: 2377ms
2-10-2016 12:55:52 > [Indexer] Next ID: 6892-7570-6012-10171-3898
2-10-2016 12:55:52 > [Indexer] Cleaning up

**Comment by licoffe** [comment]
@dukenuking I managed to get everything working on Ubuntu (http://imgur.com/vvB1c3e). Could you give it a try again when you have time?

**Comment by dukenuking** [comment]
Yes it works! Nice!
I assume the POE-price-helper should be also run with nodejs or can I just ln -s to my www forlder? =)

**Comment by licoffe** [comment]
That's great! Yeah, that's also a node app. You first need to `cd` to its directory and run `npm install`. When all dependencies have been installed, you can run it using `npm start`.

**Comment by dukenuking** [comment]
Haha you won't believe it but a wild error appeard http://pastebin.com/0wdvLJ3t
I don't think node likes Debian distro =)
I wanted to mess abit with node and picked your project =)
Edit: Probably something to do with electron not willing to start... (althou it's installed without errors)

**Comment by licoffe** [comment]
If it doesn't overwrite anything, could you try `ln /usr/bin/nodejs /usr/bin/node` and then `npm install` again?

**Comment by dukenuking** [comment]
Yeah I've done that first time I installed node, as it would not work on debian =) so I think it's something else

**Comment by licoffe** [comment]
Could you check if the electron package is properly installed in 'POE-price-helper/node_modules/electron/dist' and try to run it? I'm on mac so the path is slightly different, but you should find a binary file.

**Comment by licoffe** [comment]
Also, on OS X I'm using **node 5.2.0** and **npm 3.3.12**. On Ubuntu, I have and **node 4.2.6** and **npm 3.5.2**. That may be related.

**Comment by dukenuking** [comment]
I'll check tomorrow when I get from work =), not a fan of Ubuntu but gonna create extra vm to test out =)
Hold on, could it be that I'm using a no gui version of debian?

**Comment by licoffe** [comment]
You mean without an X server running? :D

**Comment by dukenuking** [comment]
Yes, just a simple ssh connection.

**Comment by licoffe** [comment]
Yeah, that won't work for the client (no problem for the indexer though). You need to either log in a graphical session or forward the X server through ssh using the `-X` argument, provided that this is allowed on your ssh server.

**Comment by dukenuking** [comment]
Thats what I thought, well you can close this issue then.
I'll probably write my own client to pull data out of db.

**Comment by licoffe** [comment]
Ok sure, you can take a look at the data format stored in the db. It's pretty straight forward. You can also look at the code of the client, in index.html such as the code used to query the db or to compute the average/median/mode. Good luck ;)
