### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Saturate** [licoffe/POE-Stash-indexer#4]
I just tested it, and it works fine on Windows 10?

So am I missing something, or does this indeed work on Windows?

**Comment by licoffe** [comment]
That's great news! I updated it a while back, ditching the code containing calls to 'wget' commands and 'gunzip' and replaced it by node modules for compatibility. I tried it in a virtual machine and it worked, but never tried it for real. That's good to know it works fine on your side :) I should actually update the README.
