### ISSUE TITLE
Index stops on JSON error

### ISSUE THREAD

**Issue by Saturate** [licoffe/POE-Stash-indexer#6]
My indexer stopped at the following error:

`19-10-2016 6:54:35 > [Indexer] SyntaxError: Unexpected token < in JSON at position 0`

I think it would make sense to just continue running the indexer at this point? Or maybe not, I don't why it happens, but would be nice to log some more, or just continue if we can.

**Comment by licoffe** [comment]
I managed to reproduce the issue by corrupting the JSON passed to loadJSON function. In the case where it could not parse the JSON, the program would exit. I added a setTimeout to download the JSON once again and redo the whole "parse + add to DB" process. It seems to work.
